server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
spring:
  application:
    name: page-service
    #关闭自动缓存,热部署
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.199.128
    username: admin
    password: admin
    virtual-host: /leyou