server:
  port: 8098
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.199.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  jwt:
    pubKeyPath: K:\\leyou\\key\\rsa.pub #公钥
    cookieName: LY_TOKEN #cookie name
