server:
  port: 8097
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  jwt:
    secret: leyou@xxp408395920163$com% #rsa加密盐
    pubKeyPath: K:\\leyou\\key\\rsa.pub #公钥
    priKeyPath: K:\\leyou\\key\\rsa.pri #私钥
    expire: 60 #过期时间,分钟
    cookieName: LY_TOKEN #cookie name