server:
  port: 8093
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.199.128:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.199.128
    username: admin
    password: admin
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #降低拉取服务的间隔
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true