server:
  port: 8095
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.199.128
    username: admin
    password: admin
    virtual-host: /leyou
  redis:
    host: 192.168.199.128
ly:
  sms:
    accessKeyId: LTAI4FkSAdoRq3wqCc1teAeL
    accessKeySecret: ZTKq9yS3yWicADKCauKT7nqULAPUFb
    sign: 乐优商城 #短信签名
    verifyCodeTemplate: SMS_174023066

